---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2

before:
  hooks:
    - go mod download
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - netbsd
      - openbsd
    goarch:
      - amd64
      - arm64
    main: .
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{.Version}}
    mod_timestamp: "{{ .CommitTimestamp }}"
    tags:
      - netgo
      - timetzdata

brews:
  - name: nxtp
    ids:
      - archives
    homepage: "https://github.com/kgaughan/nxtp"
    repository:
      owner: kgaughan
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    commit_author:
      name: Keith Gaughan
      email: k@stereochro.me
    description: " A Network neXt Time Protocol (NXTP) client and server"
    license: "MIT"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

archives:
  - formats:
      - tar.gz
    id: archives
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md

kos:
  - base_image: gcr.io/distroless/static:nonroot
    labels:
      org.opencontainers.image.title: NXTP
      org.opencontainers.image.description: An NXTP client and server
      org.opencontainers.image.vendor: Keith Gaughan
      org.opencontainers.image.licenses: MIT
      org.opencontainers.image.url: https://github.com/kgaughan/nxtp
      org.opencontainers.image.source: https://github.com/kgaughan/nxtp
      org.opencontainers.image.documentation: https://kgaughan.github.io/nxtp/
      org.opencontainers.image.version: "{{ .Tag }}"
      org.opencontainers.image.revision: "{{ .Commit }}"
      org.opencontainers.image.created: "{{ .Date }}"
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
      - "{{ if not .Prerelease }}latest{{ end }}"
      - "{{.Tag}}"
    creation_time: "{{.CommitTimestamp}}"
    sbom: spdx
    bare: true
    base_import_paths: true
    preserve_import_paths: false
    disable: "{{ .IsSnapshot }}"

checksum:
  algorithm: sha256
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
