#!/usr/bin/env python3

import sys
from xml.dom import minidom


def main():
    collected = {}
    for path in sys.argv[1:]:
        doc = minidom.parse(path)
        for node in doc.getElementsByTagName("mapZone"):
            if node.getAttribute("territory") != "001":
                continue
            windows_tz = node.getAttribute("other")
            iana_tz = node.getAttribute("type")
            # The original server does this pre-processing, so we should too
            collected[windows_tz.replace(" ", "").lower()] = iana_tz

    print("package main\n")
    print("// AUTOGENERATED CODE: DO NOT EDIT")
    print("var windowsTZs = map[string]string{")
    for windows_tz in sorted(collected.keys()):
        print(f'\t"{windows_tz}": "{collected[windows_tz]}",')
    print("}")


if __name__ == "__main__":
    main()
